# Generated by Django 3.2.9 on 2021-12-21 09:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idiomas',
            fields=[
                ('idioma', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('idLibro', models.PositiveIntegerField(default=0, primary_key=True, serialize=False)),
                ('titulo', models.TextField(blank=True, null=True)),
                ('autor', models.TextField(blank=True, null=True)),
                ('genero', models.TextField()),
                ('idioma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.idiomas')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.PositiveIntegerField(null=True)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('libro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.libro')),
            ],
        ),
    ]
