# Generated by Django 3.2.9 on 2021-12-21 07:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200518_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(blank=True, null=True)),
                ('autor', models.TextField(blank=True, null=True)),
                ('genero', models.TextField()),
                ('idioma', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='userinformation',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='film',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='rateDate',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='user',
        ),
        migrations.AddField(
            model_name='rating',
            name='userId',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.DeleteModel(
            name='Film',
        ),
        migrations.DeleteModel(
            name='Occupation',
        ),
        migrations.DeleteModel(
            name='UserInformation',
        ),
        migrations.AddField(
            model_name='rating',
            name='libro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.libro'),
        ),
    ]
