# Generated by Django 3.2.9 on 2021-12-21 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211221_0845'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idiomas',
            fields=[
                ('idioma', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='libro',
            name='idioma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.idiomas'),
        ),
    ]
